### ISSUE TITLE
Module 'RaxelPulse' was created for incompatible target

### ISSUE THREAD

**Issue by quanghuy-comply** [Mobile-Telematics/telematicsSDK-demoapp-flutter-#10]
I am running Xcode on M1 under Rosetta by following this article: https://docs.damoov.com/docs/ios-sdk-for-m1-processors but the same error happen on my M1 mac. I am using the example project.

I also use the first answer in  https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io/63955114#63955114.

So far I can't run the project on M1 macs, please help.

**Comment by telematicsgig** [comment]
Hey, 
I think we are talking about two errors. Please find a guide on how to fix it.

`Unable to load standard library for target 'arm64-apple-ios10.0'`

please add to the end of your project `Podfile` the following code:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'YES'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
```

[Examples](https://guides.cocoapods.org/syntax/podfile.html)


And the second error (it may be not relevant after fixing the error above)
`Module compiled with Swift 5.5.2 cannot be imported by the Swift 5.6 compiler`

[open Xcode through Rosetta - Right click on Xcode in applications folder -> Get Info -> set Open with Rosetta to true.](https://developer.apple.com/forums/thread/674582)
Make sure that `Excluded Architecture` is empty -> ![image (5)](https://user-images.githubusercontent.com/85515799/182354399-13668680-030b-4ea3-b765-3960cd7e945e.png)



[more about this case
](https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f/63955114#63955114)

**Comment by hiru-vn** [comment]
Thanks, I get a few more issues in other packages with that solution, but the final fix for me looks like this

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'YES'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
  end
end
`
