### ISSUE TITLE
Android build error - Sealed classes are not supported as program classes

### ISSUE THREAD

**Issue by pedroicandido** [Mobile-Telematics/telematicsSDK-demoapp-flutter-#17]
Hey guys, how are you? I'm trying to build your project, but I'm getting an error and I'd like your help. I have already made all the changes requested in the specifications, the only difference is that instead of using your wrapper I chose to take your SDK and place it in a folder called plugins. And now whenever I try to build this error I get this error:

<img width="983" alt="Captura de Tela 2024-06-05 às 16 00 36" src="https://github.com/Mobile-Telematics/telematicsSDK-demoapp-flutter-/assets/49328524/732613f4-f27b-4cc6-90e6-6aef2cfdedcd">

Here are some important settings from my project that you might want to see:

## android/app/build.gradle

plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '28'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 34
    namespace "com.mycompany.apps.myapp"

     compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    dependencies {
        implementation 'com.google.firebase:firebase-analytics:17.4.1'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mycompany.apps.myapp"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger() + 1
        versionName flutterVersionName
    }

    signingConfigs {
            release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

   

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    flavorDimensions "driverapp"
    productFlavors {
        dev {
            dimension "myapp"
            applicationIdSuffix ".dev"
            resValue "string", "app_name", "My App"
            versionNameSuffix ".dev"
        }
        prod {
            dimension "myapp"
            applicationId "com.mycompany.apps.myapp"
            resValue "string", "app_name", "My App"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "com.telematicssdk:tracking:2.2.260"
}

## android/settings.gradle

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.0" apply false
    id "com.google.gms.google-services" version "4.4.0" apply false
    id "com.google.firebase.crashlytics" version "2.9.9" apply false
}

include ":app"

## gradle-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip

**Comment by sgusakovsky** [comment]
Hello @pedroicandido. We noticed you use Gradle 7.6.3. Our android SDK supports Gradle 8+ versions only. We use Gradle 8.2.2 for our example project

**Comment by pedroicandido** [comment]
> Hello @pedroicandido. We noticed you use Gradle 7.6.3. Our android SDK supports Gradle 8+ versions only. We use Gradle 8.2.2 for our example project

And isn't there an older version? Because when I try to use version 8+ it gives me several incompatibility problems with other libraries.

**Comment by sgusakovsky** [comment]
@pedroicandido Only Android SDK 2.2.257 supports Gradle 7. However, this version does not work correctly on Android 14 version. That's why Gradle version has been updated for the latest version of Android SDK
