### ISSUE TITLE
Exported release app is going in the background and doesn't track 

### ISSUE THREAD

**Issue by marshmallow1234** [Mobile-Telematics/telematicsSDK-demoapp-flutter-#3]
The exported release app from example code is going in the background and doesn't track. Am i missing few steps ?

**Comment by ZangievM** [comment]
Hi, @marshmallow1234. On which system you have troubles? Android or iOS?
And also please provide us device token that you passed to SDK

**Comment by marshmallow1234** [comment]
Hi @ZangievM Thanks for the quick response.

I am using Android app created from the example. 

Device Token : 158ac82a-d0ec-4d6f-a6b2-0cb757e2ee8f

**Comment by ZangievM** [comment]
I have a couple of questions:
1. Have you enabled SDK? Is there notification from the app?
2. Please, explain us the case. You had started driving and notification haven't changed to "Your trip is being scored"?
3. Are all required permissions granted? Please visit our [troubleshooting page](https://docs.telematicssdk.com/sdk-installation/permissions-guides/troubleshooting/android-troubleshooting) to avoid issues related to phones battery optimization tools

**Comment by marshmallow1234** [comment]
@ZangievM 
1. Enabled - Notification is there
2. I didn't start driving as app keeps going in the background and notification is saying 'Not Tracking'
3. Yes, all the required permission were granted
I am attaching the video for better understanding.

https://user-images.githubusercontent.com/83299141/118505327-60366e00-b73d-11eb-94d5-054b76214df8.mp4

**Comment by ZangievM** [comment]
Ok, thank you. I will investigate your issue and return

**Comment by ZangievM** [comment]
Hi, @marshmallow1234! Please pull latest commit and try again. Issue should be resolved :)

**Comment by marshmallow1234** [comment]
Hi @ZangievM Thanks, Let me check and get back

**Comment by marshmallow1234** [comment]
@ZangievM The issue is fixed but looks like no trip data is being send if device is not in the car. I will take it in the car and see if data get's reflected in the datahub dashboard.

**Comment by ZangievM** [comment]
Hi, @marshmallow1234! You can send your issue to support@telematicssdk.com :)
