### ISSUE TITLE
Module 'RaxelPulse' was created for incompatible target

### ISSUE THREAD

**Issue by kadhikari24** [Mobile-Telematics/telematicsSDK-demoapp-flutter-#4]
I am getting the below error while running the application in ios.

Module 'RaxelPulse' was created for incompatible target arm64-apple-ios10.0

**Comment by VorobevSA** [comment]
@kadhikari24 You can look - https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io/63955114#63955114, it seems this is the solution to your problem.

**Comment by hiru-vn** [comment]
The solution above doesn't solve the problem.
I tried with the example

**Comment by VorobevSA** [comment]
@hiru-vn @kadhikari24 If you are using a Mac with an M1 processor, then you need to run XCode or Termainal under Rosetta.

**Comment by quanghuy-comply** [comment]
running with rosetta doesn't solve the problem, I followed https://docs.damoov.com/docs/ios-sdk-for-m1-processors but the same error happen on my M1 mac.
